POST http://localhost:9080/register HTTP/1.1 
Content-Type: application/json

{
  "name": "Asif",
  "userName": "asif",
  "email": "asif@gmail.com",
  "password": "1234567"
}


### To login user
POST http://localhost:9080/login HTTP/1.1 
Content-Type: application/json 


{ 
    "password":"1234567", 
    "email":"asif@gmail.com" 

} 

### To Login another User 

GET http://localhost:9080/get_user_and_profile 
Content-Type: application/json 


{
  "token": "8837771d5b2ddaa9c3dd0beab3699c322af2b043c939b977ef6f22d67f9b9076"
}

 